"""Clarifying questions for missing required fields and blocking validation errors.

Strategy
--------
1. Determine which fields are required for the current ``workflow_stage``.
2. Compute the missing subset against ``collected_data``.
3. If there are blocking validation errors (e.g. endDate before startDate),
   ask the user to correct the first offending field — even if the field is
   technically present (it just has an invalid value).
4. If any backend-derived fields are still absent, ask the user for
   ``lease_code`` (or ``lease_brand_mall`` as a fallback) so that the
   ``lease_lookup_node`` can resolve all backend fields programmatically.
5. Otherwise ask for the **first** outstanding user-supplied field — one
   question per turn.
6. When nothing is missing or invalid, surface an ``IN_PROGRESS`` status to
   unblock the next node.
"""

from __future__ import annotations

from typing import Any

from app.agents.graph.state import ServiceRequestState
from app.agents.schemas.handover_schema import STAGE_REGISTRY
from app.agents.services.missing_field_service import (
    HANDOVER_FIELD_QUESTIONS,
    get_missing_fields,
)
from app.observability.decorators import trace_node

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Fields populated exclusively by backend API lookups (lease resolution etc.).
# When any of these are missing, the node asks for a lease trigger so the
# ``lease_lookup_node`` can resolve them programmatically.
# NOTE: "title" is intentionally NOT in this set — it is auto-generated by
# merge_state_node from lease_code + description and must not trigger the
# backend-missing branch (which would block the user from being asked for
# description).
BACKEND_PROTECTED_FIELDS: frozenset[str] = frozenset(
    {
        "tenant_profile_id",
        "property_id",
        "brand_id",
        "lease_id",
        "contract_id",
        "unit_codes",
        "city",
        "contracted_area",
        "lease_brand_mall",
    }
)

# Fields that the bot must never prompt the user for but that are also not
# resolved via the lease lookup API — they are auto-generated by the system.
# These fields are silently skipped in the user_missing list so the bot
# never asks for them, while still allowing the user_missing branch to run.
_AUTO_GENERATED_FIELDS: frozenset[str] = frozenset({"title"})

# Ordered preference for the "trigger" question when backend fields are unresolved.
# Asking for lease_code first enables the most precise lookup; lease_brand_mall
# covers free-text brand/mall input when a formal code is unavailable.
_LEASE_TRIGGER_FIELDS: tuple[str, ...] = ("lease_code", "lease_brand_mall")

# Validation-error questions: maps validation_type → (field_to_ask, question_hint).
# When a blocking validation error has no entry here, fall back to the generic
# HANDOVER_FIELD_QUESTIONS for the error's field.
# Note: validate_start_end_date now returns field="endDate" so the date_range
# entry here is a fallback for any edge-case where the field is not set correctly.
_VALIDATION_ERROR_QUESTIONS: dict[str, tuple[str, str]] = {
    "date_range": (
        "endDate",
        (
            "Ask the user to provide a valid end date that is strictly after the start date. "
            "Mention the current start date and that the end date must be later."
        ),
    ),
}


# ---------------------------------------------------------------------------
# Node
# ---------------------------------------------------------------------------


@trace_node("missing_field", "AGENT")
async def missing_field_node(state: ServiceRequestState) -> dict[str, Any]:
    """Ask for exactly one missing required field per turn.

    Also handles blocking validation errors (e.g. invalid date range) by asking
    the user to correct the offending field before the form can advance.
    """
    workflow_stage: str = state.get("workflow_stage") or "CREATE_SR"

    # Gracefully degrade if an unrecognised stage arrives.
    if workflow_stage not in STAGE_REGISTRY:
        workflow_stage = "CREATE_SR"

    required: tuple[str, ...] = STAGE_REGISTRY[workflow_stage].required_fields
    collected: dict[str, Any] = state.get("collected_data") or {}
    validation_errors: list[dict[str, Any]] = state.get("validation_errors") or []

    all_missing: list[str] = get_missing_fields(collected, list(required))

    backend_missing = [f for f in all_missing if f in BACKEND_PROTECTED_FIELDS]
    # Auto-generated fields (e.g. title) are excluded from both lists — the bot
    # must not ask for them directly, and they are not resolved via lease lookup.
    user_missing = [
        f for f in all_missing
        if f not in BACKEND_PROTECTED_FIELDS and f not in _AUTO_GENERATED_FIELDS
    ]

    next_field: str | None = None
    next_question: str | None = None

    # ── Priority 0: non-required blocking validation errors ───────────────
    # "required" failures mean a field is simply absent — those are handled by
    # the backend_missing / user_missing branches below which know how to ask
    # for the right field (or resolve via lease lookup).
    #
    # Non-required failures (date_range, enum, …) mean the field IS present
    # but has an invalid value.  These must be corrected before the workflow
    # can advance, so they take priority even when other required fields are
    # still missing (e.g. endDate < startDate must be fixed before we ask for
    # inspection_done_by).
    non_required_blocking = [
        e for e in validation_errors
        if e.get("blocking", True) and e.get("validation_type") != "required"
    ]
    if non_required_blocking:
        # Pick the first non-required blocking error and ask the user to correct it.
        first_error = non_required_blocking[0]
        v_type = first_error.get("validation_type", "")
        error_field = first_error.get("field", "")

        if v_type in _VALIDATION_ERROR_QUESTIONS:
            next_field, next_question = _VALIDATION_ERROR_QUESTIONS[v_type]
        elif error_field and error_field not in BACKEND_PROTECTED_FIELDS:
            next_field = error_field
            next_question = HANDOVER_FIELD_QUESTIONS.get(
                error_field,
                f"Please correct the value for: {error_field}",
            )

    elif backend_missing:
        # One or more backend-derived fields are unresolved — ask for a lease
        # trigger so ``lease_lookup_node`` can fill them programmatically.
        for trigger in _LEASE_TRIGGER_FIELDS:
            if not collected.get(trigger):
                next_field = trigger
                next_question = HANDOVER_FIELD_QUESTIONS.get(trigger)
                break
        # If both trigger fields are already present the lease lookup simply
        # hasn't run yet — nothing more to ask; leave next_field as None.

    elif user_missing:
        # All backend fields are resolved; ask for the first user-supplied gap.
        next_field = user_missing[0]
        next_question = HANDOVER_FIELD_QUESTIONS.get(
            next_field,
            f"Please provide: {next_field}",
        )

    # When the next question is driven by a non-required validation error (e.g.
    # date_range), the correction target field may already be in collected_data
    # (it's just invalid).  Prepend it to missing_fields so that
    # field_extraction_node's hint points to the right field and the user's
    # corrected value is routed there — not to the next truly-missing field.
    effective_missing = list(all_missing)
    if next_field and next_field not in effective_missing and non_required_blocking:
        effective_missing.insert(0, next_field)

    updates: dict[str, Any] = {"missing_fields": effective_missing}

    if next_question:
        updates["response_message"] = next_question
        updates["response_ui"] = {
            "type": "text_question",
            "field": next_field,
            "message": next_question,
        }
        updates["status"] = "WAITING_FOR_USER"
    else:
        # Nothing left to ask — signal readiness for the next pipeline step.
        updates["response_message"] = ""
        updates["status"] = "IN_PROGRESS"

    return updates
