"""Workflow configuration registry — enables multi-agent / multi-lifecycle scaling.

Each agent registers a ``WorkflowConfig`` here that captures all the
per-agent knowledge that shared pipeline nodes need.  Shared nodes (e.g.
``field_extraction_node``, ``missing_field_node``, ``_route_after_sync``,
``_route_after_validation``) look up the active agent's config at runtime
instead of hard-coding rdd_agent-specific values.

Adding a new agent (e.g. rcd_agent for a renovation lifecycle)
--------------------------------------------------------------
1. Register a new ``WorkflowConfig`` in ``WORKFLOW_CONFIG_REGISTRY`` below.
2. Add the agent to ``SERVICE_REQUEST_AGENT_REGISTRY`` in ``agents/registry.py``.
3. Add the agent entry node to ``_AGENT_ENTRY_NODES`` in ``help_agent_graph.py``.
4. Add action intents to ``ROLE_PERMITTED_INTENTS`` in ``help_agent_schema.py``.
5. Update ``supervisor_prompt.py`` to describe the new intents.
6. Implement the new entry / payload / submission nodes under ``nodes/<agent>/``.
7. Wire new nodes into ``build_help_agent_graph()``.

No changes to ``field_extraction_node``, ``missing_field_node``,
``_route_after_sync``, ``_route_after_validation``, or ``HelpAgentIntent``.
"""

from __future__ import annotations

from dataclasses import dataclass, field


# ---------------------------------------------------------------------------
# WorkflowConfig dataclass
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class WorkflowConfig:
    """All per-workflow configuration that shared pipeline nodes require.

    Attributes
    ----------
    agent_name:
        Canonical ``active_agent`` value that identifies this workflow.
    extraction_prompt:
        System prompt used by ``FieldExtractionService`` when extracting fields
        for this workflow.  Each workflow should have its own domain-specific
        extraction prompt so the LLM understands the relevant field set.
    field_questions:
        Mapping of ``field_name → question_string`` used by ``missing_field_node``
        to ask the user for outstanding required fields.
    stage_sync_nodes:
        Mapping of ``workflow_stage → graph node name`` used by
        ``_route_after_sync`` to route after a platform status sync.
        Only stages that map to a specific entry node need entries here;
        terminal stages are handled separately via ``terminal_stages``.
    collection_stages:
        Set of workflow stages in which field collection (field_extraction →
        merge_state → validation loop) should run.  Stages not in this set
        short-circuit to ``response_generation`` after validation.
    confirmation_nodes:
        Mapping of ``workflow_stage → confirmation node name`` used by
        ``_route_after_validation`` when all required fields are collected.
    terminal_stages:
        Stages that mark the end of a workflow (e.g. ``SR_CREATED``,
        ``SR_COMPLETED``).  ``_route_after_sync`` routes these to ``supervisor``
        so the user can start a new intent.
    backend_fields:
        Fields resolved exclusively by backend API lookups (e.g. lease
        resolution).  ``missing_field_node`` triggers a lease-lookup question
        when any of these are missing, rather than asking the user directly.
    auto_generated_fields:
        Fields auto-generated by the system (e.g. ``title``).  These are
        silently excluded from the user-facing missing-field prompts.
    lease_trigger_fields:
        Ordered preference of fields to ask for when backend fields are
        unresolved.  Asking for the first available trigger field causes
        ``lease_lookup_node`` to fill in the rest programmatically.
    action_intents:
        Supervisor intents that activate this agent.  Used to derive
        ``_SR_ACTION_INTENTS`` in ``help_agent_graph.py`` and ``ALL_INTENTS``
        in ``help_agent_schema.py``.
    """

    agent_name: str
    extraction_prompt: str
    field_questions: dict[str, str]
    stage_sync_nodes: dict[str, str]
    collection_stages: frozenset[str]
    confirmation_nodes: dict[str, str]
    terminal_stages: frozenset[str]
    backend_fields: frozenset[str]
    auto_generated_fields: frozenset[str]
    lease_trigger_fields: tuple[str, ...]
    action_intents: frozenset[str]


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------


def _build_rdd_config() -> WorkflowConfig:
    """Build the ``WorkflowConfig`` for the RDD Agent.

    The RDD Agent handles the full RDD lifecycle:
      Phase 1 (CREATE_SR)  — Mall Manager creates the SR
      Phase 2 (FM_REVIEW)  — FM Manager / Operations inspects and adds documents
      Phase 3 (RDD_REVIEW) — DD Engineer reviews, adds documents, approves/rejects

    Deferred to a function so circular imports are avoided — the prompts and
    question maps import from schema modules that may in turn import from the
    registry during collection.
    """
    from app.agents.prompts.handover_extraction_prompt import HANDOVER_EXTRACTION_SYSTEM_PROMPT
    from app.agents.services.missing_field_service import HANDOVER_FIELD_QUESTIONS

    return WorkflowConfig(
        agent_name="rdd_agent",
        extraction_prompt=HANDOVER_EXTRACTION_SYSTEM_PROMPT,
        field_questions=HANDOVER_FIELD_QUESTIONS,
        stage_sync_nodes={
            "FM_REVIEW": "fm_review_entry",
            "RDD_REVIEW": "rdd_review_entry",
        },
        collection_stages=frozenset({"CREATE_SR", "FM_REVIEW", "RDD_REVIEW"}),
        confirmation_nodes={
            "CREATE_SR": "confirmation",
            "FM_REVIEW": "fm_confirmation",
            "RDD_REVIEW": "rdd_confirmation",
        },
        terminal_stages=frozenset({"SR_CREATED", "SR_COMPLETED"}),
        backend_fields=frozenset(
            {
                "tenant_profile_id",
                "property_id",
                "brand_id",
                "lease_id",
                "contract_id",
                "unit_codes",
                "city",
                "contracted_area",
                "lease_brand_mall",
                # 'lease' is a display label set equal to lease_code during lease
                # resolution.  Classifying it as backend-derived ensures it is
                # never surfaced as a user-facing missing-field prompt.
                "lease",
            }
        ),
        # "expected_handover_date" is auto-computed from unit_readiness_date + 7 days
        auto_generated_fields=frozenset({"title", "expected_handover_date"}),
        lease_trigger_fields=("lease_code", "lease_brand_mall"),
        action_intents=frozenset(
            {
                "CREATE_RDD_SERVICE_REQUEST",
                "UPDATE_RDD_SERVICE_REQUEST",
                "APPROVE_RDD_SERVICE_REQUEST",
            }
        ),
    )


# Registry is populated lazily via the module-level dict below.
# New workflows register here — shared nodes will pick them up automatically.
WORKFLOW_CONFIG_REGISTRY: dict[str, WorkflowConfig] = {}


def _build_work_permit_config() -> WorkflowConfig:
    """Build the ``WorkflowConfig`` for the Work Permit Agent.

    Single-stage workflow: the Mall Manager creates a work permit SR.
    There is no FM_REVIEW or RDD_REVIEW phase for work permits.
    """
    from app.agents.prompts.work_permit_extraction_prompt import (
        WORK_PERMIT_EXTRACTION_SYSTEM_PROMPT,
    )

    field_questions: dict[str, str] = {
        "lease_code": "Ask the user for the lease code associated with the unit where work will be performed.",
        "lease_brand_mall": "Ask the user for the lease code, brand name, or mall name to identify the unit.",
        "work_permit_type": (
            "Ask the user what type of work permit they need. "
            "Present the options clearly: "
            "Construction Hot Work, Construction Cold Work, Construction Roof Access, "
            "Maintenance Hot Work, Maintenance Cold Work, Maintenance Roof Access, or Operations."
        ),
        "description": "Ask the user for a brief description of the work to be performed.",
        "start_date": "Ask the user for the start date of the work permit (YYYY-MM-DD).",
        "end_date": "Ask the user for the end date of the work permit (YYYY-MM-DD).",
        "contractor_name": "Ask the user for the name of the contractor performing the work (or say 'none' if not applicable).",
        "comments": "Ask the user if they have any additional comments or instructions for this work permit request.",
    }

    return WorkflowConfig(
        agent_name="work_permit_agent",
        extraction_prompt=WORK_PERMIT_EXTRACTION_SYSTEM_PROMPT,
        field_questions=field_questions,
        stage_sync_nodes={},
        collection_stages=frozenset({"CREATE_WORK_PERMIT"}),
        confirmation_nodes={"CREATE_WORK_PERMIT": "work_permit_confirmation"},
        terminal_stages=frozenset({"WP_CREATED"}),
        backend_fields=frozenset(
            {
                "lease_id",
                "property_id",
                "unit_codes",
                "mall",
                "brand",
                "tenant_profile_id",
                "city",
                "contracted_area",
                "lease",
            }
        ),
        auto_generated_fields=frozenset(),
        lease_trigger_fields=("lease_code", "lease_brand_mall"),
        action_intents=frozenset({"CREATE_WORK_PERMIT_SR"}),
    )


def _init_registry() -> None:
    """Populate the registry with all built-in workflow configs."""
    rdd_cfg = _build_rdd_config()
    WORKFLOW_CONFIG_REGISTRY[rdd_cfg.agent_name] = rdd_cfg

    wp_cfg = _build_work_permit_config()
    WORKFLOW_CONFIG_REGISTRY[wp_cfg.agent_name] = wp_cfg


_init_registry()


# ---------------------------------------------------------------------------
# Public helpers
# ---------------------------------------------------------------------------


def get_workflow_config(agent_name: str | None) -> WorkflowConfig | None:
    """Return the ``WorkflowConfig`` for *agent_name*, or ``None`` if not registered.

    Shared nodes call this at runtime to look up per-workflow configuration
    without importing handover-specific constants directly.
    """
    return WORKFLOW_CONFIG_REGISTRY.get(agent_name or "")


def register_workflow(config: WorkflowConfig) -> None:
    """Register a custom ``WorkflowConfig`` at runtime.

    Intended for testing and for third-party workflow plugins.  Built-in
    workflows are registered in ``_init_registry()`` above.
    """
    WORKFLOW_CONFIG_REGISTRY[config.agent_name] = config


def list_registered_workflows() -> list[WorkflowConfig]:
    """Return all registered ``WorkflowConfig`` instances."""
    return list(WORKFLOW_CONFIG_REGISTRY.values())
